### ISSUE TITLE
Adding Modules

### ISSUE THREAD

**Issue by PythonJoshua** [moomooooo/Moo-Base#5]
To add modules, do I just put a .java of the module I want into the folder?
And if I added a module from another client would I have to edit all this import stuff?:
```package com.esoterik.client.features.modules.player;

import com.esoterik.client.features.modules.*;
import com.esoterik.client.features.setting.*;
import net.minecraft.init.*;
import com.esoterik.client.util.*;
import net.minecraft.block.*;
import com.esoterik.client.features.command.*;
import net.minecraft.network.*;
import net.minecraft.util.*;
import net.minecraft.network.play.client.*;
import net.minecraft.entity.*;
import net.minecraft.entity.item.*;
import net.minecraft.util.math.*;
import java.util.*;
``` (taken from gondal lol)

**Comment by Mar0Coded** [comment]
If you would want to do this you need to take the files out of the other client aswell like com.esoterik.client.util you would need that aswell and those imports you need to save aswell to make it actually work and then you need to change the com.esoterik because if you would only just copy the java file and put it in the modules folder it will not work.
